version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  server:
    container_name: server
    restart: always
    hostname: server
    build:
      context: ../
      dockerfile: docker/Dockerfile.server
    depends_on:
      - rabbitmq
    volumes:
      - "../mafia.db:/server/mafia.db:rw"
    ports:
      - "9000:9000"
  infoserver:
    container_name: infoserver
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - "../mafia.db:/infoserver/mafia.db:rw"
    build:
      context: ../
      dockerfile: docker/Dockerfile.infoserver
