// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: pkg/proto/game/state.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_UNKNOWN State = 0
	State_DAY     State = 1
	State_NIGHT   State = 2
	State_END     State = 3
	State_SPIRIT  State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "UNKNOWN",
		1: "DAY",
		2: "NIGHT",
		3: "END",
		4: "SPIRIT",
	}
	State_value = map[string]int32{
		"UNKNOWN": 0,
		"DAY":     1,
		"NIGHT":   2,
		"END":     3,
		"SPIRIT":  4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_state_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_state_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_state_proto_rawDescGZIP(), []int{0}
}

type StateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State State `protobuf:"varint,1,opt,name=state,proto3,enum=state.State" json:"state,omitempty"`
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_game_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_state_proto_rawDescGZIP(), []int{0}
}

func (x *StateResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_UNKNOWN
}

var File_pkg_proto_game_state_proto protoreflect.FileDescriptor

var file_pkg_proto_game_state_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x3d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x49, 0x47, 0x48, 0x54,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x50, 0x49, 0x52, 0x49, 0x54, 0x10, 0x04, 0x42, 0x16, 0x5a, 0x14, 0x6d, 0x61, 0x66, 0x69, 0x61,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_game_state_proto_rawDescOnce sync.Once
	file_pkg_proto_game_state_proto_rawDescData = file_pkg_proto_game_state_proto_rawDesc
)

func file_pkg_proto_game_state_proto_rawDescGZIP() []byte {
	file_pkg_proto_game_state_proto_rawDescOnce.Do(func() {
		file_pkg_proto_game_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_game_state_proto_rawDescData)
	})
	return file_pkg_proto_game_state_proto_rawDescData
}

var file_pkg_proto_game_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_game_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_game_state_proto_goTypes = []interface{}{
	(State)(0),            // 0: state.State
	(*StateResponse)(nil), // 1: state.StateResponse
}
var file_pkg_proto_game_state_proto_depIdxs = []int32{
	0, // 0: state.StateResponse.state:type_name -> state.State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_game_state_proto_init() }
func file_pkg_proto_game_state_proto_init() {
	if File_pkg_proto_game_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_game_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_game_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_game_state_proto_goTypes,
		DependencyIndexes: file_pkg_proto_game_state_proto_depIdxs,
		EnumInfos:         file_pkg_proto_game_state_proto_enumTypes,
		MessageInfos:      file_pkg_proto_game_state_proto_msgTypes,
	}.Build()
	File_pkg_proto_game_state_proto = out.File
	file_pkg_proto_game_state_proto_rawDesc = nil
	file_pkg_proto_game_state_proto_goTypes = nil
	file_pkg_proto_game_state_proto_depIdxs = nil
}
