// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: pkg/proto/connection/connection.proto

package mafia_connection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	game "mafia/pkg/proto/game"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserJoinResponse_Type int32

const (
	UserJoinResponse_OK      UserJoinResponse_Type = 0
	UserJoinResponse_EXISTS  UserJoinResponse_Type = 1
	UserJoinResponse_DEFINED UserJoinResponse_Type = 2
	UserJoinResponse_STARTED UserJoinResponse_Type = 3
)

// Enum value maps for UserJoinResponse_Type.
var (
	UserJoinResponse_Type_name = map[int32]string{
		0: "OK",
		1: "EXISTS",
		2: "DEFINED",
		3: "STARTED",
	}
	UserJoinResponse_Type_value = map[string]int32{
		"OK":      0,
		"EXISTS":  1,
		"DEFINED": 2,
		"STARTED": 3,
	}
)

func (x UserJoinResponse_Type) Enum() *UserJoinResponse_Type {
	p := new(UserJoinResponse_Type)
	*p = x
	return p
}

func (x UserJoinResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserJoinResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_connection_connection_proto_enumTypes[0].Descriptor()
}

func (UserJoinResponse_Type) Type() protoreflect.EnumType {
	return &file_pkg_proto_connection_connection_proto_enumTypes[0]
}

func (x UserJoinResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserJoinResponse_Type.Descriptor instead.
func (UserJoinResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{1, 0}
}

type UserJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserJoinRequest) Reset() {
	*x = UserJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_connection_connection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinRequest) ProtoMessage() {}

func (x *UserJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_connection_connection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinRequest.ProtoReflect.Descriptor instead.
func (*UserJoinRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{0}
}

func (x *UserJoinRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserJoinRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type UserJoinResponse_Type `protobuf:"varint,1,opt,name=type,proto3,enum=connection.UserJoinResponse_Type" json:"type,omitempty"`
}

func (x *UserJoinResponse) Reset() {
	*x = UserJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_connection_connection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinResponse) ProtoMessage() {}

func (x *UserJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_connection_connection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinResponse.ProtoReflect.Descriptor instead.
func (*UserJoinResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{1}
}

func (x *UserJoinResponse) GetType() UserJoinResponse_Type {
	if x != nil {
		return x.Type
	}
	return UserJoinResponse_OK
}

type ChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text   string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_connection_connection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_connection_connection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListParticipantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game uint32 `protobuf:"varint,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *ListParticipantsRequest) Reset() {
	*x = ListParticipantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_connection_connection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsRequest) ProtoMessage() {}

func (x *ListParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_connection_connection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ListParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{3}
}

func (x *ListParticipantsRequest) GetGame() uint32 {
	if x != nil {
		return x.Game
	}
	return 0
}

type ListParticipantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *ListParticipantsResponse) Reset() {
	*x = ListParticipantsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_connection_connection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsResponse) ProtoMessage() {}

func (x *ListParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_connection_connection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ListParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{4}
}

func (x *ListParticipantsResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type StartGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []string  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Role  game.Role `protobuf:"varint,2,opt,name=role,proto3,enum=roles.Role" json:"role,omitempty"`
	Game  uint32    `protobuf:"varint,3,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_connection_connection_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_connection_connection_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{5}
}

func (x *StartGameResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *StartGameResponse) GetRole() game.Role {
	if x != nil {
		return x.Role
	}
	return game.Role(0)
}

func (x *StartGameResponse) GetGame() uint32 {
	if x != nil {
		return x.Game
	}
	return 0
}

type ServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ServerResponse_Join
	//	*ServerResponse_Chat
	//	*ServerResponse_State
	//	*ServerResponse_Start
	//	*ServerResponse_Kill
	Response isServerResponse_Response `protobuf_oneof:"response"`
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_connection_connection_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_connection_connection_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_connection_connection_proto_rawDescGZIP(), []int{6}
}

func (m *ServerResponse) GetResponse() isServerResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ServerResponse) GetJoin() *UserJoinResponse {
	if x, ok := x.GetResponse().(*ServerResponse_Join); ok {
		return x.Join
	}
	return nil
}

func (x *ServerResponse) GetChat() *ChatResponse {
	if x, ok := x.GetResponse().(*ServerResponse_Chat); ok {
		return x.Chat
	}
	return nil
}

func (x *ServerResponse) GetState() *game.StateResponse {
	if x, ok := x.GetResponse().(*ServerResponse_State); ok {
		return x.State
	}
	return nil
}

func (x *ServerResponse) GetStart() *StartGameResponse {
	if x, ok := x.GetResponse().(*ServerResponse_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ServerResponse) GetKill() *game.KillResponse {
	if x, ok := x.GetResponse().(*ServerResponse_Kill); ok {
		return x.Kill
	}
	return nil
}

type isServerResponse_Response interface {
	isServerResponse_Response()
}

type ServerResponse_Join struct {
	Join *UserJoinResponse `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ServerResponse_Chat struct {
	Chat *ChatResponse `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type ServerResponse_State struct {
	State *game.StateResponse `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

type ServerResponse_Start struct {
	Start *StartGameResponse `protobuf:"bytes,4,opt,name=start,proto3,oneof"`
}

type ServerResponse_Kill struct {
	Kill *game.KillResponse `protobuf:"bytes,5,opt,name=kill,proto3,oneof"`
}

func (*ServerResponse_Join) isServerResponse_Response() {}

func (*ServerResponse_Chat) isServerResponse_Response() {}

func (*ServerResponse_State) isServerResponse_Response() {}

func (*ServerResponse_Start) isServerResponse_Response() {}

func (*ServerResponse_Kill) isServerResponse_Response() {}

var File_pkg_proto_connection_connection_proto protoreflect.FileDescriptor

var file_pkg_proto_connection_connection_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x72, 0x6f,
	0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0f, 0x55, 0x73, 0x65,
	0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x7f, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x34, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x49,
	0x4e, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x03, 0x22, 0x3b, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x2d, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x30,
	0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x22, 0x5e, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x72, 0x6f, 0x6c, 0x65,
	0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x67, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x22, 0x92, 0x02, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2b, 0x0a, 0x04,
	0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd3, 0x03, 0x0a, 0x0b, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x5d, 0x0a, 0x10, 0x6c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x12,
	0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x76, 0x6f,
	0x74, 0x65, 0x42, 0x61, 0x6e, 0x12, 0x17, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x56, 0x6f, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x61, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74,
	0x12, 0x14, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x13, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x07, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x17, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_connection_connection_proto_rawDescOnce sync.Once
	file_pkg_proto_connection_connection_proto_rawDescData = file_pkg_proto_connection_connection_proto_rawDesc
)

func file_pkg_proto_connection_connection_proto_rawDescGZIP() []byte {
	file_pkg_proto_connection_connection_proto_rawDescOnce.Do(func() {
		file_pkg_proto_connection_connection_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_connection_connection_proto_rawDescData)
	})
	return file_pkg_proto_connection_connection_proto_rawDescData
}

var file_pkg_proto_connection_connection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_connection_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_connection_connection_proto_goTypes = []interface{}{
	(UserJoinResponse_Type)(0),       // 0: connection.UserJoinResponse.Type
	(*UserJoinRequest)(nil),          // 1: connection.UserJoinRequest
	(*UserJoinResponse)(nil),         // 2: connection.UserJoinResponse
	(*ChatResponse)(nil),             // 3: connection.ChatResponse
	(*ListParticipantsRequest)(nil),  // 4: connection.ListParticipantsRequest
	(*ListParticipantsResponse)(nil), // 5: connection.ListParticipantsResponse
	(*StartGameResponse)(nil),        // 6: connection.StartGameResponse
	(*ServerResponse)(nil),           // 7: connection.ServerResponse
	(game.Role)(0),                   // 8: roles.Role
	(*game.StateResponse)(nil),       // 9: state.StateResponse
	(*game.KillResponse)(nil),        // 10: actions.KillResponse
	(*game.VoteBanRequest)(nil),      // 11: actions.VoteBanRequest
	(*game.ChatRequest)(nil),         // 12: actions.ChatRequest
	(*game.EndRequest)(nil),          // 13: actions.EndRequest
	(*game.CommitRequest)(nil),       // 14: actions.CommitRequest
	(*game.PublishRequest)(nil),      // 15: actions.PublishRequest
	(*game.VoteBanResponse)(nil),     // 16: actions.VoteBanResponse
	(*game.EndResponse)(nil),         // 17: actions.EndResponse
	(*game.CommitResponse)(nil),      // 18: actions.CommitResponse
	(*game.PublishResponse)(nil),     // 19: actions.PublishResponse
}
var file_pkg_proto_connection_connection_proto_depIdxs = []int32{
	0,  // 0: connection.UserJoinResponse.type:type_name -> connection.UserJoinResponse.Type
	8,  // 1: connection.StartGameResponse.role:type_name -> roles.Role
	2,  // 2: connection.ServerResponse.join:type_name -> connection.UserJoinResponse
	3,  // 3: connection.ServerResponse.chat:type_name -> connection.ChatResponse
	9,  // 4: connection.ServerResponse.state:type_name -> state.StateResponse
	6,  // 5: connection.ServerResponse.start:type_name -> connection.StartGameResponse
	10, // 6: connection.ServerResponse.kill:type_name -> actions.KillResponse
	1,  // 7: connection.MafiaServer.connect:input_type -> connection.UserJoinRequest
	4,  // 8: connection.MafiaServer.listParticipants:input_type -> connection.ListParticipantsRequest
	11, // 9: connection.MafiaServer.voteBan:input_type -> actions.VoteBanRequest
	12, // 10: connection.MafiaServer.chat:input_type -> actions.ChatRequest
	13, // 11: connection.MafiaServer.end:input_type -> actions.EndRequest
	14, // 12: connection.MafiaServer.commit:input_type -> actions.CommitRequest
	15, // 13: connection.MafiaServer.publish:input_type -> actions.PublishRequest
	7,  // 14: connection.MafiaServer.connect:output_type -> connection.ServerResponse
	5,  // 15: connection.MafiaServer.listParticipants:output_type -> connection.ListParticipantsResponse
	16, // 16: connection.MafiaServer.voteBan:output_type -> actions.VoteBanResponse
	3,  // 17: connection.MafiaServer.chat:output_type -> connection.ChatResponse
	17, // 18: connection.MafiaServer.end:output_type -> actions.EndResponse
	18, // 19: connection.MafiaServer.commit:output_type -> actions.CommitResponse
	19, // 20: connection.MafiaServer.publish:output_type -> actions.PublishResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_connection_connection_proto_init() }
func file_pkg_proto_connection_connection_proto_init() {
	if File_pkg_proto_connection_connection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_connection_connection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_connection_connection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_connection_connection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_connection_connection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListParticipantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_connection_connection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListParticipantsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_connection_connection_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_connection_connection_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_connection_connection_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ServerResponse_Join)(nil),
		(*ServerResponse_Chat)(nil),
		(*ServerResponse_State)(nil),
		(*ServerResponse_Start)(nil),
		(*ServerResponse_Kill)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_connection_connection_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_connection_connection_proto_goTypes,
		DependencyIndexes: file_pkg_proto_connection_connection_proto_depIdxs,
		EnumInfos:         file_pkg_proto_connection_connection_proto_enumTypes,
		MessageInfos:      file_pkg_proto_connection_connection_proto_msgTypes,
	}.Build()
	File_pkg_proto_connection_connection_proto = out.File
	file_pkg_proto_connection_connection_proto_rawDesc = nil
	file_pkg_proto_connection_connection_proto_goTypes = nil
	file_pkg_proto_connection_connection_proto_depIdxs = nil
}
